name: Passbolt CLI
description: >
  Passbolt command-line interface to interact with a Passbolt server via Github actions
  in an easy way.
branding:
  icon: check
  color: green
runs:
  using: docker
  image: Dockerfile
  entrypoint: "/entrypoint.sh"
  post-entrypoint: "/cleanup.sh"
inputs:
  args:
    description: Additional arguments
    required: false
  test:
    description: test argument
    required: false
