name: Passbolt CLI
description: >
  Passbolt command-line interface to interact with a Passbolt server via Github actions
  in an easy way.
branding:
  icon: check
  color: green
runs:
  using: docker
  image: Dockerfile
  entrypoint: "/entrypoint.sh"
  post-entrypoint: "/cleanup.sh"
outputs:
  out:
    description: stdout from the passbolt-cli command
  outb64:
    description: stdout from the passbolt-cli base64 encoded

inputs:
  args:
    description: Additional arguments
    required: false
  passbolt_url:
    description: The URL of the Passbolt server.
    required: true
  password:
    description: Passbolt user's password.
    required: true
  privatekey:
    description: Passbolt user's private key.
    required: true
