name: Test action

on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  test_args:
    name: args input test
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: passbolt-cli-action test args
        uses: ./
        with:
          args: >-
            "MY ARG 1"
